Hide internal headers
unikraft/lib-musl pull request #13
Opened 2022-08-19 15:46 UTC by kubanrob

This patch applies on top of #9, and includes two changes:

* Before, musl has exposed internal headers to other code, now the include paths are added to the appropriate variable.
* The rule to generate `src/internal/version.h` previously had a typo, leading to multiple definitions of VERSION.

2022-08-22 09:58 UTC, kubanrob commented
How to reproduce: Compile any app using lib-musl. Include `#include "version.h"`, this will include `musl-1.1.19/src/internal/version.h` and warn that `VERSION` is defined multiple times.

Using after merging the PR, the preprocess will not find `musl-1.1.19/src/internal/version.h` anymore (and that file will only contain one definition of `VERSION`).

2022-08-25 19:06 UTC, kubanrob commented
Update: Rebased onto latest state of thread_support (PR #9)

2022-11-09 17:41 UTC, mogasergiu requested changes
For the commit message:
s/approbate/appropriate

Otherwise, all looks good to me.

2022-11-10 18:39 UTC, kubanrob commented
**Update**: Fixed typo (thanks @mogasergiu) and rebased on top of the current `thread_support` branch.

2022-11-11 20:50 UTC, mogasergiu approved these changes
Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

2022-11-15 08:21 UTC, razvand commented
Thanks, @kubanrob . This works. I need to see whether I can approve it, or we should first integrated PR #9 and then you do a rebase.

2022-11-24 12:34 UTC, kubanrob commented
**Update**: rebased onto staging

2022-11-24 17:35 UTC, razvand approved these changes
Thanks, @kubanrob 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-24 19:41 UTC, closed without merging