Remove include directory from clean list
unikraft/lib-musl pull request #17
Opened 2022-10-25 17:30 UTC by kubanrob

The current clean rule in the Unikraft build system can not remove directories and terminated with an error if there is a directory in the list of files to clean.

This commit removes the include directory inside the lib-musl build directory from the clean list.

Since each sublibraries has a separate subdirectories in the include directory, this change will not make headers accessible which would have been deleted by the clean rule.

Alternatives considered:

1. Enable the build build rule to remove directories.
This would lead to the uk_clean_list not containing a complete lists of files to remove anymore and makes the potencial damage of errors in the clean list much higher.

2. Add every header file into the `LIBMUSL_CLEAN` variable.
This could be done in `_libmusl_import_lib` and would remove the linked headers, but would still leave the directory tree.

3. Do not create the links, but include from the origin directory.
This would remove the ability to filter header files in the sublibrary makefile.

2022-11-08 20:56 UTC, mogasergiu requested changes
Some nitpicks for some minor typos in the commit message:
s/sublibraries has a/sublibrary has
You wrote `build` twice in the first alternative's description.
s/potencial/potential

I guess a simple `LIBMUSL_CLEAN += -r $(LIBMUSL_BUILD)/include` would be too ugly for a workaround :).

Otherwise, it looks good and I find the second alternative to be the least intrusive.

2022-11-09 10:26 UTC, kubanrob commented
Thank you for finding these typos @mogasergiu.

> I guess a simple LIBMUSL_CLEAN += -r $(LIBMUSL_BUILD)/include would be too ugly for a workaround :).

The list entries are separated by spaces, so this could also cause problems.

2022-11-09 17:34 UTC, mogasergiu commented
> Thank you for finding these typos @mogasergiu.
> 
> > I guess a simple LIBMUSL_CLEAN += -r $(LIBMUSL_BUILD)/include would be too ugly for a workaround :).
> 
> The list entries are separated by spaces, so this could also cause problems.

Yeah, I mostly meant it as a joke. But it did work on my end :P.

2022-11-09 17:37 UTC, mogasergiu approved these changes
Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

2022-11-15 10:54 UTC, razvand approved these changes
Thanks, @kubanrob 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-17 09:27 UTC, closed without merging