[DRAFT] Upgrade musl to latest version (1.2.3)
unikraft/lib-musl pull request #34
Opened 2022-12-11 11:05 UTC by eduardvintila

Signed-off-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2022-12-15 18:03 UTC, StefanJum commented on Makefile.uk.musl.misc
> +LIBMUSL_MISC_SRCS-y += $(LIBMUSL)/src/misc/getresuid.c
Any reason why the `getresuid` source file is compiled only when `POSIX_USER` is not enabled?
The `getresuid` wrapper should not be defined by `posix_user`, since musl disables libc-style wrappers, so always compiling the sources makes sense.
I get an `undefined reference` error when trying to build `python3`.

2022-12-17 14:46 UTC, eduardvintila commented on Makefile.uk.musl.misc
> +LIBMUSL_MISC_SRCS-y += $(LIBMUSL)/src/misc/getresuid.c
No reason at all, just me being sloppy. Thanks for noticing this!

2023-01-30 16:34 UTC, StefanJum approved these changes
Looks good @eduardvintila, I tested it with all the apps and it does not seem to break anything. Thanks a lot.
I'll wait for @razvand to review it and then leave the tag.

2023-01-31 16:29 UTC, razvand requested changes
Hi, @eduardvintila. This looks good. Please remove the commented out lines in Makefile files.

Also, I want to merge #32 and #33 first, with @mschlumpp's work (also reviewed by @StefanJum). That may require you to a rebase of this PR, and then we merge everything.

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.thread
> +#LIBMUSL_THREAD_SRCS-y += $(LIBMUSL)/src/thread/clone.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.thread
> +#LIBMUSL_THREAD_SRCS-y += $(LIBMUSL)/src/thread/__set_thread_area.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.thread
> +#LIBMUSL_THREAD_SRCS-y += $(LIBMUSL)/src/thread/syscall_cp.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.thread
> +#LIBMUSL_THREAD_SRCS-y += $(LIBMUSL)/src/thread/__unmapself.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.math
> +#LIBMUSL_MATH_SRCS-y += $(LIBMUSL)/src/math/acosl.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.math
> +#LIBMUSL_MATH_SRCS-y += $(LIBMUSL)/src/math/asinl.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.math
> +#LIBMUSL_MATH_SRCS-y += $(LIBMUSL)/src/math/atan2l.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.math
> +#LIBMUSL_MATH_SRCS-y += $(LIBMUSL)/src/math/atanl.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.math
> +#LIBMUSL_MATH_SRCS-y += $(LIBMUSL)/src/math/ceill.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.math
> +#LIBMUSL_MATH_SRCS-y += $(LIBMUSL)/src/math/exp2l.c
Why not just remove this?

2023-01-31 16:29 UTC, razvand commented on Makefile.uk.musl.math
> +LIBMUSL_MATH_SRCS-y += $(LIBMUSL)/src/math/__expo2.c
Why not just remove this?

2023-01-31 16:54 UTC, eduardvintila commented
@razvand, I've removed all the commented out lines. Will do a rebase again after those PRs are merged 👍🏻

2023-02-01 06:48 UTC, razvand commented
@eduardvintila, I tested this, it looks great. We'll wait for PR #32 and #33 to be merged. You will need to do a slight update to your PR (I tested with all of them included). Then I will approve.

2023-02-01 08:12 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-02-01 09:54 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-02-01 10:02 UTC, closed without merging