Makefile.uk: Add flag to avoid gcc specifc symbol
unikraft/lib-musl pull request #38
Opened 2023-03-11 15:41 UTC by mariasfiraiala

When building apps with `clang` for `x86`, an asm specific symbol, `__muldc3`, which results in a undefined reference error, at link time.

This PR adds the `-ffast-math` flag, when `clang` is used in order to fix this issue.

2023-03-14 11:29 UTC, StefanJum reviewed
Thanks @mariasfiraiala, it works on my side.
Since it feels a little tricky, would it make sense to add this only if `libmath` is selected in musl?

2023-03-20 09:35 UTC, mariasfiraiala commented
@StefanJum I've amended the commit. Regarding adding the dependency on the `libmath` config, the problem actually resides in the `libcomplex` part `musl`, so I've set the dependency accordingly.

2023-03-20 10:06 UTC, StefanJum requested changes

2023-03-20 10:06 UTC, StefanJum commented on Makefile.uk
> +ifeq ($(LIBMUSL_COMPLEX),y)
```suggestion
ifeq ($(CONFIG_LIBMUSL_COMPLEX),y)
```

2023-03-20 10:15 UTC, StefanJum approved these changes
All good now, thanks @mariasfiraiala.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-05-04 14:17 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-05-04 14:29 UTC, closed without merging