Fix C++ build issues w/ LLVM 16 (C++17 support)
unikraft/lib-musl pull request #45
Opened 2023-05-04 10:03 UTC by andreittr

A set of fixes to enable building alongside LLVM libcxx:
- syscall type mismatch (by @mschlumpp )
- prlimit64 not defined (by @mschlumpp )
- patch file number duplication
- ioctl signature mismatch
- wrong macro set in build options
- missing declaration for prctl

Part of a patch set w/ further PRs under libcxx, libcxxabi, lib-compiler-rt & libunwind.

2023-05-05 11:39 UTC, rares-miculescu approved these changes
It works for me. Thanks, @andreittr!

Reviewed-by: Rares Miculescu <miculescur@gmail.com>

2023-05-06 09:06 UTC, StefanJum requested changes
@andreittr the [ioctl signature commit](https://github.com/unikraft/lib-musl/pull/45/commits/ae4b8bf7526655a2dfa86b7e3089eee491eb2835) is already covered by [this](https://github.com/unikraft/lib-musl/commit/cb8f2dab68eb1ad5b1604617c52077557125210c), please remove that one.

2023-05-08 08:31 UTC, andreittr commented
> @andreittr the [ioctl signature commit](https://github.com/unikraft/lib-musl/pull/45/commits/ae4b8bf7526655a2dfa86b7e3089eee491eb2835) is already covered by [this](https://github.com/unikraft/lib-musl/commit/cb8f2dab68eb1ad5b1604617c52077557125210c), please remove that one.

Thanks for the heads-up, removed and rebased.

2023-05-27 12:17 UTC, StefanJum approved these changes
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-06-01 15:32 UTC, razvand approved these changes
I tested this as well, and it works as expected. Thanks, @andreittr.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2023-06-01 19:15 UTC, eduardvintila approved these changes
Thanks, everyone!

Approved-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2023-06-01 19:28 UTC, closed without merging