Revert "Makefile.uk: Add flag to avoid gcc specifc symbol"
unikraft/lib-musl pull request #46
Opened 2023-05-05 07:36 UTC by andreittr

This reverts commit 4912487a42ec9ab1f7ab7bcca698c50a849eafa8.

`__muldc3` is implemented by `lib-compiler-rt` for clang, and emitting calls to it is normal. While -ffast-math prevents these calls, it also enables unsafe optimizations that might result in wrong results from math functions. Best to just pull in lib-compiler-rt when needed.

2023-05-06 07:28 UTC, mariasfiraiala approved these changes
>  While -ffast-math prevents these calls, it also enables unsafe optimizations that might result in wrong results from math functions. Best to just pull in lib-compiler-rt when needed.

Fair enough @andreittr! Thanks for pointing this out.  I still think we need to find an easier approach to solve this problem. Having `compiler-rt` pulled for every app that one would want to compile with `clang` seems a little to cumbersome.

However, since last night, when [this series of patches](https://github.com/unikraft/unikraft/pull/700) got merged, building with `clang` fails anyway:

```Makefile
<instantiation>:15:20: error: invalid register name
 .cfi_offset rflags, 8
                   ^
/home/maria/release/unikraft/plat/kvm/x86/cpu_vectors_x86_64.S:142:1: note: while in macro instantiation
TRAP_ENTRY divide_error, 0
^
<instantiation>:15:20: error: invalid register name
 .cfi_offset rflags, 8
                   ^
/home/maria/release/unikraft/plat/kvm/x86/cpu_vectors_x86_64.S:143:1: note: while in macro instantiation
TRAP_ENTRY debug, 0
^
```

As a conclusion, my comments regarding `compiler-rt` don't really matter right now, as nothing really works :smile:. Thank you for your fix and let's merge it.

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-05-06 07:35 UTC, StefanJum requested changes
I wouldn't pull `compiler-rt` every time we compile something with `musl`. It looks like a lot of unneeded extra stuff.
If the issue only appears when using `compiler-rt`, can't we do something like this?
```makefile
ifneq($(CONFIG_LIBCOMPILER_RT), y)
LIBMUSL_CFLAGS-$(call have_clang) += -ffast-math
endif
```

2023-05-06 07:49 UTC, mariasfiraiala commented
>  If the issue only appears when using `compiler-rt`, can't we do something like this?
> 
> ```makefile
> ifneq($(CONFIG_LIBCOMPILER_RT), y)
> LIBMUSL_CFLAGS-$(call have_clang) += -ffast-math
> endif
> ```

As far as I understand, the issue appears when `compiler-rt` **is not** present. That's why, back when I checked complex apps compilation with `clang`, the build failed: they weren't using `compiler-rt`. So, your Makefile suggestion, @StefanJum, should be negated (I believe):

```Makefile
ifneq($(CONFIG_LIBCOMPILER_RT), n)
```

That's what you meant @andreittr, right?

2023-05-07 12:22 UTC, razvand commented
@mariasfiraiala, we fixed the `clang`-building issue here: https://github.com/unikraft/unikraft/pull/877

2023-05-07 12:55 UTC, mariasfiraiala commented
> @mariasfiraiala, we fixed the `clang`-building issue here: [unikraft/unikraft#877](https://github.com/unikraft/unikraft/pull/877)

Nice thing, thanks @razvand @StefanJum! Now, regarding the `__muldc3` issue, I think @StefanJum's suggestion is the way to go, as:

1. It's easy, and doesn't imply pulling `lib-compiler-rt` for every app.

1. Even though `-ffast-math` might produce build errors with (very) new versions of `clang`, one can still pull `lib-compiler-rt` as an emergency and build their app nevertheless.

@andreittr what do you think?

2023-05-08 08:13 UTC, andreittr commented
> I wouldn't pull compiler-rt every time we compile something with musl. It looks like a lot of unneeded extra stuff.
If the issue only appears when using compiler-rt, can't we do something like this?

From what I can tell, compiling musl with clang emits `__muldc3` iff complex numbers are enabled (`CONFIG_LIBMUSL_COMPLEX`) so pulling in `lib-compiler-rt` is not required for all apps that use musl, only strictly for those that need complex number support.

> Even though -ffast-math might produce build errors with (very) new versions of clang, one can still pull lib-compiler-rt as an emergency and build their app nevertheless.

The build errors with clang 16 are at compile-time and refer to (1) musl (via pragmas) requesting certain guarantees on floating-point maths and (2) clang being unable to provide those guarantees due to `-ffast-math`, so pulling in `lib-compiler-rt` will not help in that case (missing `__muldc3` errors are at link-time, but that's much later).

2023-05-10 12:49 UTC, razvand commented
> edit: I agree that pulling in `lib-compiler-rt` (and, therefore, _an entire C++ runtime_) only for `__muldc3` is ridiculous, and a better solution is needed. My thoughts are to split up `lib-compiler-rt` into the essential builtins (like implementing float ops) and extra stuff (like unwinding & what else is in `gcc_personality_v0.c`) but that's for another time.

@andreittr, please create an issue as part of the [`lib-compiler-rt` repository](https://github.com/unikraft/lib-compiler-rt/) with this.

2023-05-10 17:19 UTC, StefanJum approved these changes
All good as long as #47 gets merged.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-05-10 17:46 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-05-10 18:00 UTC, closed without merging