README: Update description of Musl support
unikraft/lib-musl pull request #49
Opened 2023-05-11 11:42 UTC by razvand

The contents of the `README.md` file are not up-to-date. Replace them with a short description of Musl, and point out that Musl is the default Unikraft libc.

2023-05-11 12:14 UTC, kubanrob requested changes
Looks good, however I am not sure if the information about `lib-newlib` is correct.

2023-05-11 12:14 UTC, kubanrob commented on README.md
> +`newlib` also requires [`pthread-embedded`](https://github.com/unikraft/lib-pthread-embedded/), while Musl doesn't.
This looks not completely correct to me.

As far as I understand: `lib-newlib` does not support pthreads (`newlib` might do), so `lib-pthread-embedded` is required to use pthreads with `lib-newlib`. The other way around, `lib-pthread-embedded` is not compatible with `lib-musl`.

2023-05-11 12:14 UTC, kubanrob commented on README.md
> +`newlib` also requires [`pthread-embedded`](https://github.com/unikraft/lib-pthread-embedded/), while Musl doesn't.
At this point it might be good also mentioning that `nolibc` provides a minimal subset of libc required for the kernel.

2023-05-11 14:43 UTC, razvand commented
> Looks good, however I am not sure if the information about `lib-newlib` is correct.

Thanks, @kubanrob. I updated the README addressing your comments.

2023-05-11 17:08 UTC, mariasfiraiala requested changes
Small comment on my part (you'll find the suggestion below). Also, I wonder whether it's worth mentioning the `clang` - `compiler-rt` - `__muldc3` issue. Even though not many people use `clang`, it's good for documentation purposes

2023-05-11 17:08 UTC, mariasfiraiala commented on README.md
> +Musl doesn't require (and must not be built with) `pthread-embedded.
```suggestion
Musl doesn't require (and must not be built with) `pthread-embedded`.
```

2023-05-12 12:06 UTC, razvand commented
> Small comment on my part (you'll find the suggestion below). Also, I wonder whether it's worth mentioning the `clang` - `compiler-rt` - `__muldc3` issue. Even though not many people use `clang`, it's good for documentation purposes

@mariasfiraiala , done.

2023-05-12 13:22 UTC, mariasfiraiala approved these changes
Looks ok, thanks @razvand!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-05-12 17:31 UTC, eduardvintila requested changes
Hey, @razvand. Looks good, thanks for this. There is only one sentence which I would have it rephrased.

2023-05-12 17:31 UTC, eduardvintila commented on README.md
> +Note that networking support [`lwip`](https://github.com/unikraft/lib-lwip) is required.
```suggestion
Note that [`lwip`](https://github.com/unikraft/lib-lwip) is required for networking support.
```

One could understand that networking support is mandatory for all musl builds, which obviously is not the case.

2023-05-15 09:12 UTC, kubanrob commented
Thank you @razvand!

Reviewed-by: Robert Kuban <robert.kuban@opensynergy.com>

2023-05-15 09:13 UTC, kubanrob approved these changes

2023-05-15 09:17 UTC, eduardvintila approved these changes
Thanks, @razvand!

Approved-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2023-05-15 09:39 UTC, closed without merging