Re-enable wrappers
unikraft/lib-musl pull request #5
Opened 2022-05-07 09:19 UTC by dragosargint

This PR will re-enable the wrappers in musl.
This PR is dependent on unikraft.sched.refactor (Simon's private Branch) as well as these PRs:
https://github.com/unikraft/unikraft/pull/454
https://github.com/unikraft/unikraft/pull/453
https://github.com/unikraft/unikraft/pull/442
https://github.com/unikraft/unikraft/pull/441

2022-05-17 10:58 UTC, mogasergiu approved these changes
It works for me.

Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

2022-11-19 23:43 UTC, skuenzer requested changes
Hi @dragosargint,

I basically only stumbed across a slight incorrect description in the headers of two patch files. I would also like ot ask you to change the commit subject of the last commit of this PR to mention `ioctl`. In the description you can mention that the patch is no longer needed because xyz.

Thanks,

Simon

2022-11-19 23:43 UTC, skuenzer commented on patches/0005-lib-musl-Use-uk_syscall_r-for-do_setxid.patch
> +we will use the `uk_syscall_r()` macro from syscall shim. This
```diff
-we will use the `uk_syscall_r()` macro from syscall shim. This
+we will use `uk_syscall_r()` from syscall shim. This
```

2022-11-19 23:43 UTC, skuenzer commented on patches/0005-lib-musl-Use-uk_syscall_r-for-__syscall_cp_c.patch
> +we will use the `uk_syscall_r()` macro from syscall shim. This
It is all correct except `uk_syscall_r()` is not a macro, it is a function provided by syscall_shim. 😉 
```diff
-we will use the `uk_syscall_r()` macro from syscall shim. This
+we will use `uk_syscall_r()` from syscall shim. This
```

2022-11-19 23:43 UTC, skuenzer commented on patches/0005-lib-musl-Use-uk_syscall_r-for-__syscall_cp_c.patch
> ++		return uk_syscall_r(nr, u, v, w, x, y, z);
Because the number of arguments are 6, here you could use the syscall variant that does not use a variadic list: `uk_syscall6_r()`.

2022-11-23 09:39 UTC, skuenzer approved these changes
Thanks a lot. Looks fine to me.

Reviewed-by: Simon Kuenzer <simon@unikraft.io>
Approved-by: Simon Kuenzer <simon@unikraft.io>

2022-11-23 10:17 UTC, closed without merging