glue: Init libc.auxv to point to a zero value
unikraft/lib-musl pull request #53
Opened 2023-05-31 17:27 UTC by StefanJum

The `libc.auxv` is not supposed to be 0, since it will be dereferenced by any call to `getauxval`.
It should point to a 0 value instead.

2023-05-31 19:45 UTC, mschlumpp requested changes
Thanks for the PR, I added one comment.

2023-05-31 19:45 UTC, mschlumpp commented on __uk_init_tls.c
Just one request: You can create a static global variable for the array and reference that one instead of allocating on the heap.

2023-05-31 20:22 UTC, StefanJum commented
Done @mschlumpp, thanks.

2023-06-01 06:44 UTC, mschlumpp approved these changes
Reviewed-by: Marco Schlumpp <marco@unikraft.io>

2023-06-01 11:18 UTC, razvand commented
@StefanJum, should we then close [PR `913` in the Unikraft core repository](https://github.com/unikraft/unikraft/pull/913)?

2023-06-01 11:24 UTC, StefanJum commented
> @StefanJum, should we then close [PR `913` in the Unikraft core repository](https://github.com/unikraft/unikraft/pull/913)?

Yes, closed.

2023-06-28 12:54 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-06-28 13:21 UTC, closed without merging