Makefile.uk: Condition TCB reserve on Kconfig
unikraft/lib-musl pull request #54
Opened 2023-06-07 10:50 UTC by andreittr

Previously musl's Makefile would unconditionally reserve a TCB size, regardless of whether musl was selected for build in Kconfig. This change makes this reservation happen only when musl is selected.

2023-07-01 06:42 UTC, StefanJum requested changes
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-08 13:25 UTC, eduardvintila reviewed
Hey, @andreittr. Good addition! 

While we're at it, I think the `aarch64_no_reserved_tcb_overlap` rule should also include a similar check, so please add one there, as well. Thanks!

2023-07-19 08:09 UTC, andreittr commented
Update: rebased & added new commits

2023-07-31 13:44 UTC, razvand reviewed
This looks good to me. Tested and it works. @StefanJum, @eduardvintila, please add your review  / approval, and then I'll add the final approval step.

2023-08-04 18:04 UTC, StefanJum approved these changes
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-06 10:48 UTC, eduardvintila approved these changes
Thank you!

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2023-08-07 15:00 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-07 20:20 UTC, andreittr commented
Rebased on staging.

2023-08-10 17:31 UTC, closed without merging