Option to handle DNS requesets by lwIP
unikraft/lib-musl pull request #74
Opened 2024-02-06 13:48 UTC by skuenzer

This PR introduces an option to use lwIP's DNS resolution for `getaddrinfo()`, `getnameinfo()`, `gethostbyname()`, and family. It can be enabled if lwIP is available. It will enable lwIP's DNS and socket interfaces.
The advantages of this implementation is that
1) there needs to place an `/etc/resolv.conf` in the VFS,
2) Works with DNS servers that lwIP got assigned with a DHCP reply.

2024-02-06 19:28 UTC, StefanJum requested changes
@skuenzer I get some redefinition errors when building, am I missing something in the config step?

```
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:9:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/liblwip/origin/fork-lwip-UNIKRAFT-2_1_x/src/include/lwip/netdb.h:92:8: error: redefinition of ‘struct hostent’
   92 | struct hostent {
      |        ^~~~~~~
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:8:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/libmusl/include/network/include/netdb.h:69:8: note: originally defined here
   69 | struct hostent {
      |        ^~~~~~~
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:9:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/liblwip/origin/fork-lwip-UNIKRAFT-2_1_x/src/include/lwip/netdb.h:103:8: error: redefinition of ‘struct addrinfo’
  103 | struct addrinfo {
      |        ^~~~~~~~
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:8:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/libmusl/include/network/include/netdb.h:16:8: note: originally defined here
   16 | struct addrinfo {
      |        ^~~~~~~~
/media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:13:17: error: conflicting types for ‘gethostbyname’; have ‘struct hostent *(const char *)’
   13 | struct hostent *gethostbyname(const char *name) {
      |                 ^~~~~~~~~~~~~
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:8:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/libmusl/include/network/include/netdb.h:116:17: note: previous declaration of ‘gethostbyname’ with type ‘struct hostent *(const ’
  116 | struct hostent *gethostbyname (const char *);
      |                 ^~~~~~~~~~~~~
/media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:17:17: error: conflicting types for ‘gethostbyname2’; have ‘struct hostent *(const char *, int)’
   17 | struct hostent *gethostbyname2(const char *name __unused, int af __unused) {
      |                 ^~~~~~~~~~~~~~
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:8:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/libmusl/include/network/include/netdb.h:135:17: note: previous declaration of ‘gethostbyname2’ with type ‘struct hostent *(const’
  135 | struct hostent *gethostbyname2(const char *, int);
      |                 ^~~~~~~~~~~~~~
/media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:27:5: error: conflicting types for ‘gethostbyname_r’; have ‘int(const char *, struct hostent *, char *, size_t,  struct ho}
   27 | int gethostbyname_r(const char *name, struct hostent *ret, char *buf,
      |     ^~~~~~~~~~~~~~~
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:8:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/libmusl/include/network/include/netdb.h:133:5: note: previous declaration of ‘gethostbyname_r’ with type ‘int(const char *, stru}
  133 | int gethostbyname_r(const char *, struct hostent *, char *, size_t, struct hostent **, int *);
      |     ^~~~~~~~~~~~~~~
/media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:33:5: error: conflicting types for ‘gethostbyname2_r’; have ‘int(const char *, int,  struct hostent *, char *, size_t,  st}
   33 | int gethostbyname2_r(const char *name __unused, int af __unused,
      |     ^~~~~~~~~~~~~~~~
In file included from /media/stefan/projects/unikraft/maintainer-tools/workdir/libs/musl/lwip/gethostbyname.c:8:
/media/stefan/projects/unikraft/maintainer-tools/workdir/apps/nginx/workdir/build/libmusl/include/network/include/netdb.h:134:5: note: previous declaration of ‘gethostbyname2_r’ with type ‘int(const char *, int}
  134 | int gethostbyname2_r(const char *, int, struct hostent *, char *, size_t, struct hostent **, int *);
```

2024-02-06 22:01 UTC, skuenzer commented
Ouh sorry, you need to have the following lwip PR also applied. Sorry, I forgot to mention that dependency in the description: https://github.com/unikraft/lib-lwip/pull/48

2024-02-07 06:58 UTC, StefanJum approved these changes
All good now, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-02-08 21:28 UTC, Mihnea0Firoiu approved these changes
All good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

2024-02-09 20:32 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-02-09 20:32 UTC, merged