Thread support for musl
unikraft/lib-musl pull request #9
Opened 2022-08-14 22:55 UTC by dragosargint

This PR contains essential changes for thread support in musl. This PR is currently a superset of https://github.com/unikraft/lib-musl/pull/5 , which will need to be merged first. This PR is dependent on:
[1] Simon's uksched refactor: https://github.com/skuenzer/unikraft/tree/skuenzer/sched-refactor
[2] [unikraft/unikraft#454](https://github.com/unikraft/unikraft/pull/454)
[3] [unikraft/unikraft#453](https://github.com/unikraft/unikraft/pull/453)
[4][ unikraft/unikraft#442](https://github.com/unikraft/unikraft/pull/442)
[5][ unikraft/unikraft#441](https://github.com/unikraft/unikraft/pull/441)

[4] Cannot be automatically be merged into [1] right now, I will provide a patch on discord

2022-08-17 10:12 UTC, craciunoiuc reviewed
I did a first pass through all the files/commits and only found a few typos.

One mention: some of the commits have a pretty long commit title, try reducing them if possible.

Other than this, good work! I'll come back after testing it.

2022-08-17 10:12 UTC, craciunoiuc commented on __uk_init_tls.c
> + * If the pthread API is usead, musl will allocate the TLS and will
```suggestion
 * If the pthread API is used, musl will allocate the TLS and will
```

2022-08-17 10:12 UTC, craciunoiuc commented on __uk_init_tls.c
> + * in fact a conigous region which will have the following layout (Please
```suggestion
 * in fact a contiguous region which will have the following layout (Please
```

2022-08-17 10:12 UTC, craciunoiuc commented on __uk_init_tls.c
> +	 * syscall, to set the tid user space addres in the Kernel.
```suggestion
	 * syscall, to set the tid user space address in the Kernel.
```

2022-08-17 10:12 UTC, craciunoiuc commented on __uk_init_tls.c
> +	uk_pr_debug("uk_thread_tcb_fini uk_thraed %p, tcb %p\n", thread, tcb);
```suggestion
	uk_pr_debug("uk_thread_tcb_fini uk_thread %p, tcb %p\n", thread, tcb);
```

2022-08-19 08:38 UTC, craciunoiuc commented
All good from my side now, waiting on the other reviewers to add the tag.

2022-08-22 20:56 UTC, maniatro111 commented
The PR looks good. I just have one question. Should we write somewhere that in order to make the clone wrapper function work, `CLONE_VM`, `CLONE_FILES` and `CLONE_FS` should be added as flags?

2022-08-23 16:26 UTC, dragosargint commented
> The PR looks good. I just have one question. Should we write somewhere that in order to make the clone wrapper function work, `CLONE_VM`, `CLONE_FILES` and `CLONE_FS` should be added as flags?

The flags are not added, they are default in musl for creating threads as we discussed. Indeed, in the release documentation, it should be mentioned that the `clone()' syscall only works for creating threads. Therefore, these flags must be used.

2022-08-23 19:07 UTC, maniatro111 commented
Looks good.
Reviewed-by: Florin Postolache <florin.postolache80@gmail.com>

2022-08-24 10:07 UTC, kubanrob commented
It seems like `Makefile.uk.musl.process:#LIBMUSL_PROCESS_SRCS-y += $(LIBMUSL)/src/process/waitpid.c` needs to be commented in to build with the current Unikraft branch.

2022-08-24 13:35 UTC, razvanvirtan commented
> 

Yes, it happened to me too (I think you mean uncommented?)

2022-08-24 17:25 UTC, dragosargint commented
> It seems like `Makefile.uk.musl.process:#LIBMUSL_PROCESS_SRCS-y += $(LIBMUSL)/src/process/waitpid.c` needs to be commented in to build with the current Unikraft branch.

Hi, Robert! Thank you for your comment! You are right, that source must be uncommented from the Makefile. I modified this PR https://github.com/unikraft/lib-musl/pull/5 and rebased this one as well.

2022-10-07 12:00 UTC, kubanrob commented on __uk_init_tls.c
> +	td->tid = uk_syscall_r_set_tid_address(&td->tid);
This effectively sets the tid of the main thread to -95. This tid is then used, in the implementation of recursive mutexes, causing `pthread_mutex_unlock` to fail.

```suggestion
	 * it returns an error code (-95, -ENOTSUP) because posix_process_init has not been
	 * called at this stage, but will be called via uk_late_initcall.
	 * It is not a really big problem right now. Since this is the main thread,
	 * nobody should ever wait for it, and we can just assume thread id 0.
	 */
	td->tid = uk_syscall_r_set_tid_address(&td->tid);
	if (td->tid < 0) {
		td->tid = 0;
	}
```

2022-10-26 21:04 UTC, dragosargint commented on __uk_init_tls.c
> +	td->tid = uk_syscall_r_set_tid_address(&td->tid);
Hello, Robert. Thank you for your comment. You are right, the tid can be set to 0 here.

2022-11-02 12:40 UTC, kubanrob commented
@dragosargint Can you please change my information to `Robert Kuban <robert.kuban@opensynergy.com>` in commit 2a3c2a0? Yours are generated by the web interface as well.

2022-11-06 16:49 UTC, razvand requested changes

2022-11-06 16:49 UTC, razvand commented on __uk_init_tls.c
> +	ukplat_tlsp_set(TP_ADJ(p));
```suggestion
	ukplat_tlsp_set((unsigned long) TP_ADJ(p));
```

To suppress a warning.

2022-11-07 21:55 UTC, dragosargint commented on __uk_init_tls.c
> +	ukplat_tlsp_set(TP_ADJ(p));
Thank you for your comment!

2022-11-07 21:55 UTC, dragosargint commented
> @dragosargint Can you please change my information to `Robert Kuban <robert.kuban@opensynergy.com>` in commit [2a3c2a0](https://github.com/unikraft/lib-musl/commit/2a3c2a0ae6dd4f1d1fa48af30f64eef110be0559)? Yours are generated by the web interface as well.

2022-11-08 10:07 UTC, kubanrob commented
Just 2 minor things:
- Space missing in commit message of eef2f0e03bf7be9ebeafa14376cf08e4ec97ba01: "is used.We are"
- Patch 15 is duplicated in 1e83a3ece0428a172fc71709f63229d66ccf535b just to be deleted in 46f65b5932832424c239b99089b9a6fc5a7fc659

2022-11-10 14:10 UTC, craciunoiuc reviewed
Two small things from me 🙈

`lib-musl: remove no longer required patch` -> `lib-musl: Remove no longer required patch`
`Set tid to 0 for the main thread` -> `lib-musl: Set tid to 0 for the main thread`

2022-11-23 12:44 UTC, razvand requested changes
Hi, @dragosargint . See some cosmetic comments from my side.

2022-11-23 12:44 UTC, razvand commented on Makefile.uk
> +# This will reserve space within `uk_tls` for the pthread structure in musl
```suggestion
# This will reserve space within `uk_tls` for the pthread structure in Musl.
```

2022-11-23 12:44 UTC, razvand commented on Makefile.uk
> +# For this musl version the size of "struct pthread" is 280
```suggestion
# For this version of Musl the size of "struct pthread" is 280.
```

2022-11-23 12:44 UTC, razvand commented on Makefile.uk.musl.thread
> +#LIBMUSL_THREAD_SRCS-y += $(LIBMUSL)/src/thread/i386/__set_thread_area.s|i386
Shouldn't the commented out lines simply be removed?

2022-11-23 12:44 UTC, razvand commented on __set_thread_area.c
> + * Copyright (c) 2022, University Politehnica of Bucharest. All rights reserved.
```suggestion
 * Copyright (c) 2022, University POLITEHNICA of Bucharest. All rights reserved.
```

2022-11-23 12:44 UTC, razvand commented on __uk_init_tls.c
> + * Copyright (c) 2022, University Politehnica of Bucharest. All rights reserved.
```suggestion
 * Copyright (c) 2022, University POLITEHNICA of Bucharest. All rights reserved.
```

2022-11-23 12:44 UTC, razvand commented on __uk_unmapself.c
> + * Copyright (c) 2022, University Politehnica of Bucharest. All rights reserved.
```suggestion
 * Copyright (c) 2022, University POLITEHNICA of Bucharest. All rights reserved.
```

2022-11-23 14:08 UTC, skuenzer requested changes
Hey,
Dragos, please check my comments inline. I assume ukmmap is in use because of the musl code, right? If so, ignore my comment regarding the dependency.

Besides the left comments, I would change the subject of the followin gpatches:
`Add patch for pthread_create.c` -> `pthread-create: TLS alignment and cleanup`
`Delete and rename some patches` -> `Remove obsolete patches`

Thanks,

Simon

2022-11-23 14:08 UTC, skuenzer commented on Config.uk
> +  select LIBUKMMAP
Is mmap still used for the threading? If not, can we remove this dependency?

2022-11-23 14:08 UTC, skuenzer commented on __uk_init_tls.c
> +		td->tid = 0;
You may want to add to this commit the Config.uk option is selected that initializes the main thread id to 0.

2022-11-23 17:46 UTC, dragosargint commented on Makefile.uk.musl.thread
> +#LIBMUSL_THREAD_SRCS-y += $(LIBMUSL)/src/thread/i386/__set_thread_area.s|i386
There are several such lines commented out in the Makefiles in Musl. From my point of view, it is better to leave them commented out to see what is used from the real sources and what is not, or defined as glue code. That's why I just commented and not removed them.

2022-11-23 17:48 UTC, dragosargint commented
> Hi, @dragosargint . See some cosmetic comments from my side.

Thank you for the comments, @razvand. I applied your suggestions.

2022-11-23 17:49 UTC, dragosargint commented on Config.uk
> +  select LIBUKMMAP
We still need it :))

2022-11-23 19:16 UTC, kubanrob reviewed
Looking add the code again, I found some things that are not clear to me.

I think a few comments what function is indented to be called from where would help making the glue code more understandable.

2022-11-23 19:16 UTC, kubanrob commented on __uk_init_tls.c
> +/*
This comment should probably go above the function definition.

2022-11-23 19:16 UTC, kubanrob commented on __uk_init_tls.c
> +static volatile size_t __uk_tsd_size = sizeof(void *) * PTHREAD_KEYS_MAX;
Is there a reason that this is a static volatile variable? I don't see it referenced elsewhere and it looks like it should be an constant.

2022-11-23 19:16 UTC, kubanrob commented on __uk_init_tls.c
> +static int __uk_init_tp(void *p)
I think a comment that says that this function should only be called for the main thread would help understanding this code. (if that is true.)

2022-11-23 19:16 UTC, kubanrob commented on __uk_init_tls.c
> +		return 0;
`__uk_init_tls` is only setting a subset of the tcb members set later in the function (eg. `td->tsd`). Is that on purpose?

2022-11-23 20:46 UTC, dragosargint commented on __uk_init_tls.c
> +static volatile size_t __uk_tsd_size = sizeof(void *) * PTHREAD_KEYS_MAX;
I was actually copying it from musl code. I think we can remove the volatile keyword
```
volatile size_t __pthread_tsd_size = sizeof(void *) * PTHREAD_KEYS_MAX;
```

2022-11-23 20:48 UTC, dragosargint commented on __uk_init_tls.c
> +/*
Yes, it should

2022-11-23 20:56 UTC, dragosargint commented on __uk_init_tls.c
> +static int __uk_init_tp(void *p)
It is true. It is the initialisation of the `pthread_structure` for the main thread. The other threads (created with the pthread API) will have this structure populated by the `pthread_create()` function.

2022-11-23 21:05 UTC, dragosargint commented on __uk_init_tls.c
> +		return 0;
The `uk_thread_uktcb_init()` callback should be called for all threads that are not created via `clone()`. This means TLS allocated by unikraft, not by libc and passed through `clone()` to unikraft. The main thread is not created via `clone()` so `uk_thread_uktcb_init()` is called . `__uk_init_tls()` is called only once in the entire application and is only for the main thread, because after it executes it sets the libc.can_do_threads to 1.  What is below this if is for threads that are not created with `clone()' but that we want to run with musl.

2022-11-23 21:12 UTC, dragosargint commented on __uk_init_tls.c
> +		return 0;
Here is the __init_tp for the main thread in musl
```
int __init_tp(void *p)
{
        pthread_t td = p;
        td->self = td;
        int r = __set_thread_area(TP_ADJ(p));
        if (r < 0) return -1;
        if (!r) libc.can_do_threads = 1;
        td->tid = __syscall(SYS_set_tid_address, &td->tid);
        td->locale = &libc.global_locale;
        td->robust_list.head = &td->robust_list.head;
        return 0;
}
```

2022-11-23 21:20 UTC, dragosargint commented on __uk_init_tls.c
> +		return 0;
And you might wonder why there's no tsd for the main thread. Well, there is but is set on demand :))
```
int __pthread_key_create(pthread_key_t *k, void (*dtor)(void *))
{
...
        if (!self->tsd) self->tsd = __pthread_tsd_main;
}
```

2022-11-23 21:42 UTC, craciunoiuc reviewed
Some small styling comments from my side

2022-11-23 21:42 UTC, craciunoiuc commented on Makefile.uk
> +# Please refer to ./arch/Makefile.rules fore more details.
```suggestion
# Please refer to ./arch/Makefile.rules for more details.
```

2022-11-23 21:42 UTC, craciunoiuc commented on __set_thread_area.c
> +/*
```suggestion
 */
 
#include <uk/sched.h>

/*
```

2022-11-23 21:42 UTC, craciunoiuc commented on __uk_unmapself.c
> +void __uk_unmapself(void *base, size_t size)
```suggestion
static __uk_tls struct __map_area __per_thread_map_area = {};

void __uk_unmapself(void *base, size_t size)
```

2022-11-23 22:45 UTC, dragosargint commented on __uk_init_tls.c
> +		return 0;
I now see that `uk_thread_uktcb_init()` is not called for the main thread. So `__uk_init_tls()` should be moved from there. But the other points are valid.

2022-11-24 01:34 UTC, skuenzer approved these changes
Thanks @dragosargint, the updates look good!

Reviewed-by: Simon Kuenzer <simon@unikraft.io>
Approved-by: Simon Kuenzer <simon@unikraft.io>

2022-11-24 09:35 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2022-11-24 11:53 UTC, razvand approved these changes
Tested it, it works.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-24 11:54 UTC, kubanrob approved these changes
Looks good, thank you @dragosargint 

Reviewed-by: Robert Kuban <robert.kuban@opensynergy.com>

2022-11-24 11:57 UTC, closed without merging